name: Builder

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set date env var
        run: echo "::set-env name=run_date::$(date "+%Y%m%dT%H%M")"

          
     - name: Checkout
       uses: actions/checkout@master
      

    - name: docker-compose version
      run: docker-compose --version
    - name: npm install cache
      id: npm-install
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-node_modules
    
    - name: npm install
      if: steps.npm-install.outputs.cache-hit != true
      run: | 
        npm install
        
    - name: Composer install
      run: |
        npm run composer

    - name: working dir stuff
      run: | 
        whoami
        id
        pwd
        ls -la wp-content/themes/action-test/
        chmod 0777 wp-content/themes/action-test/
        chmod 0777 .
        ls -la .
        ls -la wp-content/themes/action-test/
  
  
    - name: try building
      run: sudo npm run build
      
    
    - name: so we failed, what'd we get?
      run: | 
        ls -la wp-content/themes/action-test
#       uses: ideasonpurpose/docker-build@master
#       with: 
#         args: npm run build
