name: Release Maker

on: 
  push: 
    tags: ["v*"]
    branches: "*"

jobs:
  # test-action:
  # runs-on: ubuntu-latest
  # name: Testing the action I just made
  # steps:
  #   - name: Hello acton
  #     id: hello
  #     uses: joemaller/managed-wordpress-deploy@master
  #     with:
  #       remote-host: gip7b70f58129a.ssh.wpengine.net

  #   - name: followup
  #     run: echo "Here's the output ${{ steps.hello.outputs.time }}"

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      # - name: Set environment vars
      #   run: |
      #     echo  "RUN_DATE=$(date "+%Y%m%dT%H%M")" >> $GITHUB_ENV

      - name: Set up REPO and TAG (hash) environment vars
        run: |
          echo "THEME_NAME=$(jq -r '.name' package.json)" >> $GITHUB_ENV
          echo "REPO=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          echo "TAG=${GITHUB_SHA:0:6}" >> $GITHUB_ENV

      - name: This run was triggered by a version tag, reset the $TAG variable to the tag name
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo  "TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: env
        run: env

      - name: npm install
        run: npm ci

      - name: Create Zip Archive
        run: |
          rm -rf ${THEME_NAME}.zip
          zip -r ${THEME_NAME}.zip wp-content/themes/${THEME_NAME} -i wp-content/themes/${THEME_NAME}/index.php wp-content/themes/${THEME_NAME}/lib/\*

      - name: Only run for tags
        if: contains(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo 'This must be a tag'
          gh release create $TAG ${THEME_NAME}.zip

      - name: Test jq
        run: |
          jq --version

      - name: Test gh
        run: |
          gh --version
  
      - name: Store Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ REPO }}
          path: |
            wp-content/themes/action-test/screenshot.png
            wp-content/themes/action-test/src/*
            README.md
          retention-days: 2

