name: Release Maker

on: [push]

jobs:
  # test-action:
  # runs-on: ubuntu-latest
  # name: Testing the action I just made
  # steps:
  #   - name: Hello acton
  #     id: hello
  #     uses: joemaller/managed-wordpress-deploy@master
  #     with:
  #       remote-host: gip7b70f58129a.ssh.wpengine.net

  #   - name: followup
  #     run: echo "Here's the output ${{ steps.hello.outputs.time }}"

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Set environment vars
        run: |
          echo "::set-env name=RUN_DATE::$(date "+%Y%m%dT%H%M")"
          echo "::set-env name=THEME_NAME::$(jq '.name' package.json)"

      - name: env
        run: env

      - name: npm install
        run: npm ci

      - name: Zip it up
        id: zip
        run: echo ${{ steps.zip.name }}
      
      - name: Only run for tags
        if: contains(github.ref, 'refs/tags/')
        run: echo 'This must be a tag'

      - name: Test s3
        run: |
          aws --version
          aws s3 ls $S3_URI

      - name: Test gh
        run: |
          gh --version

