name: Builder

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Run a one-line script
      run: echo Hello, world! $(date "+%H:%M:%S")

#     - name: Try npm
#       run: npm version

    - name: try building
      uses: ideasonpurpose/docker-build
      with: 
        args: npm run build
