name: Builder

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      
    - name: Run a one-line script
      run: echo Hello, world! $(date "+%H:%M:%S")

    - name: docker-compose version
      run: docker-compose --version
    
    - name: Install stuff
      run: | 
        npm install
        npm run composer

    - name: user?
      run: | 
        whoami
        pwd
  
    - name: sudo user?
      run: |
        sudo whoami
        sudo pwd
      
    - name: env?
      run: env
  
#     - name: try building
#       run: npm run build
      
#       uses: ideasonpurpose/docker-build@master
#       with: 
#         args: npm run build
