name: Release Maker

on: [push]

jobs:
  # test-action:
  # runs-on: ubuntu-latest
  # name: Testing the action I just made
  # steps:
  #   - name: Hello acton
  #     id: hello
  #     uses: joemaller/managed-wordpress-deploy@master
  #     with:
  #       remote-host: gip7b70f58129a.ssh.wpengine.net

  #   - name: followup
  #     run: echo "Here's the output ${{ steps.hello.outputs.time }}"

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@master

      # - name: Set environment vars
      #   run: |
      #     echo  "RUN_DATE=$(date "+%Y%m%dT%H%M")" >> $GITHUB_ENV
      #     echo  "THEME_NAME=$(jq '.name' package.json)" >> $GITHUB_ENV

      - name: Set up REPO and TAG (hash) environment vars
        run: |
          echo  "REPO=${GITHUB_REPOSITORY#*/}" >> $GITHUB_ENV
          echo "TAG=${GITHUB_SHA:0:6}" >> $GITHUB_ENV

      - name: This run was triggered by a version tag, reset the $TAG variable to the tag name
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          echo  "TAG=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: env
        run: env

      - name: npm install
        run: npm ci

      - name: Zip it up
        id: zip
        run: echo ${{ steps.zip.name }}

      - name: Create Zip Archive
        run: |
          rm -rf ${REPO}.zip
          zip -r ${REPO}.zip ${REPO} -i wp-content/themes/${REPO}/index.php wp-content/themes/${REPO}/lib/\* ${REPO}/vendor/\*

      - name: Only run for tags
        if: contains(github.ref, 'refs/tags/')
        run: echo 'This must be a tag'

      - name: Test s3
        run: |
          aws --version

      - name: Test gh
        run: |
          gh --version
