name: Builder

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master
      
#     - name: Run a one-line script
#       run: echo Hello, world! $(date "+%H:%M:%S")

    - name: docker-compose version
      run: docker-compose --version
    
    - name: Install stuff
      run: | 
        npm install
        npm run composer

    - name: working dir stuff
      run: | 
        whoami
        pwd
        ls -la wp-content/themes/action-test/
        chmod 0777 wp-content/themes/action-test/
        ls -la wp-content/themes/action-test/
  
  
    - name: try building
      run: sudo npm run build
      
    
    - name: so we failed, what'd we get?
      run: | 
        ls -la wp-content/themes/action-test
#       uses: ideasonpurpose/docker-build@master
#       with: 
#         args: npm run build
