# This is a basic workflow to help you get started with Actions

name: Manual Run Detector

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      trigger:
        description: 'Switch to use SHA instead of tags on manual builds'
        required: false
        default: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run on Pull
        if: github.event_name == "pull"
        run: |
          echo "${GITHUB_REF}"
          echo "${GITHUB_REF#refs/tags/v}"
      - name: Run on workflow_dispatch
        if: github.event_name == "workflow_dispatch"
        run: |
          echo "${GITHUB_SHA}"
          echo "${GITHUB_SHA:0:6}"
        

